"""Official FIFA WC2026 third-placed team allocation table (Regulations, Annexe C).

The Round-of-32 candidate sets in ``bracket.py`` only *constrain* where each best-third can go;
they do not pin it down — every one of the 495 possible qualifying-third combinations admits
several legal matchings. FIFA resolves this with a fixed lookup table (Annexe C, "Combinations for
eight best third-placed teams"): given *which* eight groups produced the qualifying thirds, the
table states exactly which third faces each group winner. This module reproduces that table verbatim
so the simulator schedules the real R32 third-place matchups rather than an arbitrary valid one.

Source: FWC26 Regulations, Annexe C (parsed from the published PDF; all 495 rows).

Each entry of ``_ROWS`` is one Annexe-C option: the eight third-place groups listed in
*winner-column* order — i.e. the group whose third faces Winner A, then Winner B, D, E, G, I, K, L.
"""

from __future__ import annotations

# Group winners (in Annexe-C column order) that face a best-third in the Round of 32.
WINNER_COLUMNS = "ABDEGIKL"

# fmt: off
_ROWS: list[str] = [
    "EJIFHGLK", "HGIDJFLK", "EJIDHGLK", "EJIDHFLK", "EGIDJFLK", "EGJDHFLK",
    "EGIDHFLK", "EGJDHFLI", "EGJDHFIK", "HGICJFLK", "EJICHGLK", "EJICHFLK",
    "EGICJFLK", "EGJCHFLK", "EGICHFLK", "EGJCHFLI", "EGJCHFIK", "HGICJDLK",
    "CJIDHFLK", "CGIDJFLK", "CGJDHFLK", "CGIDHFLK", "CGJDHFLI", "CGJDHFIK",
    "EJICHDLK", "EGICJDLK", "EGJCHDLK", "EGICHDLK", "EGJCHDLI", "EGJCHDIK",
    "CJEDIFLK", "CJEDHFLK", "CEIDHFLK", "CJEDHFLI", "CJEDHFIK", "CGEDJFLK",
    "CGEDIFLK", "CGEDJFLI", "CGEDJFIK", "CGEDHFLK", "CGJDHFLE", "CGJDHFEK",
    "CGEDHFLI", "CGEDHFIK", "CGJDHFEI", "HJBFIGLK", "EJIBHGLK", "EJBFIHLK",
    "EJBFIGLK", "EJBFHGLK", "EGBFIHLK", "EJBFHGLI", "EJBFHGIK", "HJBDIGLK",
    "HJBDIFLK", "IGBDJFLK", "HGBDJFLK", "HGBDIFLK", "HGBDJFLI", "HGBDJFIK",
    "EJBDIHLK", "EJBDIGLK", "EJBDHGLK", "EGBDIHLK", "EJBDHGLI", "EJBDHGIK",
    "EJBDIFLK", "EJBDHFLK", "EIBDHFLK", "EJBDHFLI", "EJBDHFIK", "EGBDJFLK",
    "EGBDIFLK", "EGBDJFLI", "EGBDJFIK", "EGBDHFLK", "HGBDJFLE", "HGBDJFEK",
    "EGBDHFLI", "EGBDHFIK", "HGBDJFEI", "HJBCIGLK", "HJBCIFLK", "IGBCJFLK",
    "HGBCJFLK", "HGBCIFLK", "HGBCJFLI", "HGBCJFIK", "EJBCIHLK", "EJBCIGLK",
    "EJBCHGLK", "EGBCIHLK", "EJBCHGLI", "EJBCHGIK", "EJBCIFLK", "EJBCHFLK",
    "EIBCHFLK", "EJBCHFLI", "EJBCHFIK", "EGBCJFLK", "EGBCIFLK", "EGBCJFLI",
    "EGBCJFIK", "EGBCHFLK", "HGBCJFLE", "HGBCJFEK", "EGBCHFLI", "EGBCHFIK",
    "HGBCJFEI", "HJBCIDLK", "IGBCJDLK", "HGBCJDLK", "HGBCIDLK", "HGBCJDLI",
    "HGBCJDIK", "CJBDIFLK", "CJBDHFLK", "CIBDHFLK", "CJBDHFLI", "CJBDHFIK",
    "CGBDJFLK", "CGBDIFLK", "CGBDJFLI", "CGBDJFIK", "CGBDHFLK", "CGBDHFLJ",
    "HGBCJFDK", "CGBDHFLI", "CGBDHFIK", "HGBCJFDI", "EJBCIDLK", "EJBCHDLK",
    "EIBCHDLK", "EJBCHDLI", "EJBCHDIK", "EGBCJDLK", "EGBCIDLK", "EGBCJDLI",
    "EGBCJDIK", "EGBCHDLK", "HGBCJDLE", "HGBCJDEK", "EGBCHDLI", "EGBCHDIK",
    "HGBCJDEI", "CJBDEFLK", "CEBDIFLK", "CJBDEFLI", "CJBDEFIK", "CEBDHFLK",
    "CJBDHFLE", "CJBDHFEK", "CEBDHFLI", "CEBDHFIK", "CJBDHFEI", "CGBDEFLK",
    "CGBDJFLE", "CGBDJFEK", "CGBDEFLI", "CGBDEFIK", "CGBDJFEI", "CGBDHFLE",
    "CGBDHFEK", "HGBCJFDE", "CGBDHFEI", "HJIFAGLK", "EJIAHGLK", "EJIFAHLK",
    "EJIFAGLK", "EGJFAHLK", "EGIFAHLK", "EGJFAHLI", "EGJFAHIK", "HJIDAGLK",
    "HJIDAFLK", "IGJDAFLK", "HGJDAFLK", "HGIDAFLK", "HGJDAFLI", "HGJDAFIK",
    "EJIDAHLK", "EJIDAGLK", "EGJDAHLK", "EGIDAHLK", "EGJDAHLI", "EGJDAHIK",
    "EJIDAFLK", "HJEDAFLK", "HEIDAFLK", "HJEDAFLI", "HJEDAFIK", "EGJDAFLK",
    "EGIDAFLK", "EGJDAFLI", "EGJDAFIK", "HGEDAFLK", "HGJDAFLE", "HGJDAFEK",
    "HGEDAFLI", "HGEDAFIK", "HGJDAFEI", "HJICAGLK", "HJICAFLK", "IGJCAFLK",
    "HGJCAFLK", "HGICAFLK", "HGJCAFLI", "HGJCAFIK", "EJICAHLK", "EJICAGLK",
    "EGJCAHLK", "EGICAHLK", "EGJCAHLI", "EGJCAHIK", "EJICAFLK", "HJECAFLK",
    "HEICAFLK", "HJECAFLI", "HJECAFIK", "EGJCAFLK", "EGICAFLK", "EGJCAFLI",
    "EGJCAFIK", "HGECAFLK", "HGJCAFLE", "HGJCAFEK", "HGECAFLI", "HGECAFIK",
    "HGJCAFEI", "HJICADLK", "IGJCADLK", "HGJCADLK", "HGICADLK", "HGJCADLI",
    "HGJCADIK", "CJIDAFLK", "HJFCADLK", "HFICADLK", "HJFCADLI", "HJFCADIK",
    "CGJDAFLK", "CGIDAFLK", "CGJDAFLI", "CGJDAFIK", "HGFCADLK", "CGJDAFLH",
    "HGJCAFDK", "HGFCADLI", "HGFCADIK", "HGJCAFDI", "EJICADLK", "HJECADLK",
    "HEICADLK", "HJECADLI", "HJECADIK", "EGJCADLK", "EGICADLK", "EGJCADLI",
    "EGJCADIK", "HGECADLK", "HGJCADLE", "HGJCADEK", "HGECADLI", "HGECADIK",
    "HGJCADEI", "CJEDAFLK", "CEIDAFLK", "CJEDAFLI", "CJEDAFIK", "HEFCADLK",
    "HJFCADLE", "HJECAFDK", "HEFCADLI", "HEFCADIK", "HJECAFDI", "CGEDAFLK",
    "CGJDAFLE", "CGJDAFEK", "CGEDAFLI", "CGEDAFIK", "CGJDAFEI", "HGFCADLE",
    "HGECAFDK", "HGJCAFDE", "HGECAFDI", "HJBAIGLK", "HJBAIFLK", "IJBFAGLK",
    "HJBFAGLK", "HGBAIFLK", "HJBFAGLI", "HJBFAGIK", "EJBAIHLK", "EJBAIGLK",
    "EJBAHGLK", "EGBAIHLK", "EJBAHGLI", "EJBAHGIK", "EJBAIFLK", "EJBFAHLK",
    "EIBFAHLK", "EJBFAHLI", "EJBFAHIK", "EJBFAGLK", "EGBAIFLK", "EJBFAGLI",
    "EJBFAGIK", "EGBFAHLK", "HJBFAGLE", "HJBFAGEK", "EGBFAHLI", "EGBFAHIK",
    "HJBFAGEI", "IJBDAHLK", "IJBDAGLK", "HJBDAGLK", "IGBDAHLK", "HJBDAGLI",
    "HJBDAGIK", "IJBDAFLK", "HJBDAFLK", "HIBDAFLK", "HJBDAFLI", "HJBDAFIK",
    "FJBDAGLK", "IGBDAFLK", "FJBDAGLI", "FJBDAGIK", "HGBDAFLK", "HGBDAFLJ",
    "HGBDAFJK", "HGBDAFLI", "HGBDAFIK", "HGBDAFIJ", "EJBAIDLK", "EJBDAHLK",
    "EIBDAHLK", "EJBDAHLI", "EJBDAHIK", "EJBDAGLK", "EGBAIDLK", "EJBDAGLI",
    "EJBDAGIK", "EGBDAHLK", "HJBDAGLE", "HJBDAGEK", "EGBDAHLI", "EGBDAHIK",
    "HJBDAGEI", "EJBDAFLK", "EIBDAFLK", "EJBDAFLI", "EJBDAFIK", "HEBDAFLK",
    "HJBDAFLE", "HJBDAFEK", "HEBDAFLI", "HEBDAFIK", "HJBDAFEI", "EGBDAFLK",
    "EGBDAFLJ", "EGBDAFJK", "EGBDAFLI", "EGBDAFIK", "EGBDAFIJ", "HGBDAFLE",
    "HGBDAFEK", "HGBDAFEJ", "HGBDAFEI", "IJBCAHLK", "IJBCAGLK", "HJBCAGLK",
    "IGBCAHLK", "HJBCAGLI", "HJBCAGIK", "IJBCAFLK", "HJBCAFLK", "HIBCAFLK",
    "HJBCAFLI", "HJBCAFIK", "CJBFAGLK", "IGBCAFLK", "CJBFAGLI", "CJBFAGIK",
    "HGBCAFLK", "HGBCAFLJ", "HGBCAFJK", "HGBCAFLI", "HGBCAFIK", "HGBCAFIJ",
    "EJBAICLK", "EJBCAHLK", "EIBCAHLK", "EJBCAHLI", "EJBCAHIK", "EJBCAGLK",
    "EGBAICLK", "EJBCAGLI", "EJBCAGIK", "EGBCAHLK", "HJBCAGLE", "HJBCAGEK",
    "EGBCAHLI", "EGBCAHIK", "HJBCAGEI", "EJBCAFLK", "EIBCAFLK", "EJBCAFLI",
    "EJBCAFIK", "HEBCAFLK", "HJBCAFLE", "HJBCAFEK", "HEBCAFLI", "HEBCAFIK",
    "HJBCAFEI", "EGBCAFLK", "EGBCAFLJ", "EGBCAFJK", "EGBCAFLI", "EGBCAFIK",
    "EGBCAFIJ", "HGBCAFLE", "HGBCAFEK", "HGBCAFEJ", "HGBCAFEI", "IJBCADLK",
    "HJBCADLK", "HIBCADLK", "HJBCADLI", "HJBCADIK", "CJBDAGLK", "IGBCADLK",
    "CJBDAGLI", "CJBDAGIK", "HGBCADLK", "HGBCADLJ", "HGBCADJK", "HGBCADLI",
    "HGBCADIK", "HGBCADIJ", "CJBDAFLK", "CIBDAFLK", "CJBDAFLI", "CJBDAFIK",
    "HFBCADLK", "CJBDAFLH", "HJBCAFDK", "HFBCADLI", "HFBCADIK", "HJBCAFDI",
    "CGBDAFLK", "CGBDAFLJ", "CGBDAFJK", "CGBDAFLI", "CGBDAFIK", "CGBDAFIJ",
    "CGBDAFLH", "HGBCAFDK", "HGBCAFDJ", "HGBCAFDI", "EJBCADLK", "EIBCADLK",
    "EJBCADLI", "EJBCADIK", "HEBCADLK", "HJBCADLE", "HJBCADEK", "HEBCADLI",
    "HEBCADIK", "HJBCADEI", "EGBCADLK", "EGBCADLJ", "EGBCADJK", "EGBCADLI",
    "EGBCADIK", "EGBCADIJ", "HGBCADLE", "HGBCADEK", "HGBCADEJ", "HGBCADEI",
    "CEBDAFLK", "CJBDAFLE", "CJBDAFEK", "CEBDAFLI", "CEBDAFIK", "CJBDAFEI",
    "HFBCADLE", "HEBCAFDK", "HJBCAFDE", "HEBCAFDI", "CGBDAFLE", "CGBDAFEK",
    "CGBDAFEJ", "CGBDAFEI", "HGBCAFDE",
]
# fmt: on

# frozenset of the eight qualifying-third groups -> {winner_group: third_group}.
THIRD_ALLOCATION: dict[frozenset[str], dict[str, str]] = {
    frozenset(row): {WINNER_COLUMNS[i]: row[i] for i in range(8)} for row in _ROWS
}


def allocate_thirds(qualified_third_groups: list[str]) -> dict[str, str]:
    """Return the official Annexe-C mapping ``winner_group -> third_group`` for these eight thirds.

    ``qualified_third_groups`` are the eight groups whose third-placed team qualified. Raises
    ``KeyError`` if the combination is not one of the 495 valid Annexe-C options.
    """
    return THIRD_ALLOCATION[frozenset(qualified_third_groups)]
